#Docker compose file for starting common resources

version: '3'

# Postgres 15
services:
  postgres:
    image: postgres:13.6-alpine
    container_name: spring-tutorial-postgres
    restart: always
    volumes:
      - spring_tutorial_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  mongo_spring_boot_tutorial:
    image: mongo:5.0
    restart: always
    container_name: mongo_spring_boot_tutorial
    environment:
      MONGO_INITDB_ROOT_USERNAME: bookstore
      MONGO_INITDB_ROOT_PASSWORD: bookstore
      MONGO_INITDB_DATABASE: bookstore
    ports:
      - "27021:27017"
volumes:
    spring_tutorial_postgres_data:
